export const styles = {
  container: { minHeight: '100vh', background: 'linear-gradient(135deg, #fbc2eb 0%, #a6c1ee 100%)', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', fontFamily: 'sans-serif', padding: '20px', overflowX: 'hidden', transition: 'background 0.5s ease' },
  loginCard: { background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(12px)', padding: '40px', borderRadius: '20px', textAlign: 'center', border: '1px solid rgba(255,255,255,0.3)' },
  input: { padding: '12px', borderRadius: '10px', border: 'none', marginTop: '15px', textAlign: 'center', width: '200px', outline: 'none' },
  button: { padding: '12px 20px', borderRadius: '10px', border: 'none', backgroundColor: '#ff85a2', color: '#fff', cursor: 'pointer', marginTop: '15px', fontWeight: 'bold' },
  popupSurpresaOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(8px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 2000 },
  popupSurpresaContent: { background: '#fdfbf7', padding: '40px', borderRadius: '20px', textAlign: 'center', maxWidth: '400px', width: '90%', border: '2px solid #ff85a2', boxShadow: '0 10px 30px rgba(0,0,0,0.3)', display: 'flex', flexDirection: 'column', alignItems: 'center', boxSizing: 'border-box' },

  header: { position: 'fixed', top: 0, left: 0, width: '100%', padding: '15px 25px', boxSizing: 'border-box', display: 'flex', justifyContent: 'space-between', alignItems: 'center', zIndex: 1000 },
  menuToggleBtn: { position: 'relative', pointerEvents: 'auto', background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(10px)', border: '1px solid rgba(255,255,255,0.2)', color: '#fff', padding: '10px', borderRadius: '12px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 4px 15px rgba(0,0,0,0.2)' },
  mercadoIconBtn: { pointerEvents: 'auto', border: '2px solid #ff4655', borderRadius: '4px', width: '35px', height: '40px', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', boxShadow: '0 0 8px rgba(255, 70, 85, 0.4)', transition: 'background 0.3s', flexShrink: 0, margin: 0 },
  smallDiamond: { width: '10px', height: '10px', background: '#ff4655', transform: 'rotate(45deg)' },

  badgeNotificacao: { position: 'absolute', top: '-6px', right: '-6px', background: '#ff4655', color: '#fff', fontSize: '0.7rem', fontWeight: 'bold', width: '18px', height: '18px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '50%', boxShadow: '0 0 10px rgba(255,70,85,0.8)' },
  badgeNotificacaoSidebar: { position: 'absolute', top: '-5px', right: '-8px', background: '#ff4655', color: '#fff', fontSize: '0.65rem', fontWeight: 'bold', padding: '2px 6px', borderRadius: '10px', boxShadow: '0 0 10px rgba(255,70,85,0.6)' },

  sidebarOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.4)', backdropFilter: 'blur(4px)', zIndex: 1001, cursor: 'pointer' },
  sidebarNav: { position: 'fixed', top: 0, left: 0, width: '280px', height: '100vh', background: 'rgba(15, 25, 35, 0.95)', backdropFilter: 'blur(15px)', zIndex: 1002, display: 'flex', flexDirection: 'column', padding: '25px 20px', boxSizing: 'border-box', borderRight: '1px solid rgba(255,255,255,0.1)', boxShadow: '5px 0 30px rgba(0,0,0,0.5)' },
  sidebarHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '35px', borderBottom: '1px solid rgba(255,255,255,0.1)', paddingBottom: '15px' },
  closeMenuBtn: { background: 'none', border: 'none', color: '#aaa', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  sidebarMenuGrid: { display: 'flex', flexDirection: 'column', gap: '10px' },
  sidebarBtn: { width: '100%', padding: '12px 18px', borderRadius: '12px', border: 'none', background: 'transparent', color: '#ccc', fontSize: '1rem', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '12px', textAlign: 'left', transition: '0.2s' },
  sideNavBtnActive: { width: '100%', padding: '12px 18px', borderRadius: '12px', border: 'none', background: '#ff85a2', color: '#fff', fontSize: '1rem', fontWeight: 'bold', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '12px', textAlign: 'left', boxShadow: '0 4px 15px rgba(255,133,162,0.4)' },
  navBtnActiveStyle: { width: '100%', padding: '12px 18px', borderRadius: '12px', border: 'none', background: '#ff85a2', color: '#fff', fontSize: '1rem', fontWeight: 'bold', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '12px', textAlign: 'left', boxShadow: '0 4px 15px rgba(255,133,162,0.4)' },

  grid: { display: 'flex', gap: '25px', flexWrap: 'wrap', justifyContent: 'center', marginTop: '100px', maxWidth: '1000px' },
  cardFrame: { background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(12px)', border: '1px solid rgba(255,255,255,0.3)', width: '240px', height: '185px', padding: '10px', borderRadius: '20px', cursor: 'pointer' },
  imageContainer: { width: '100%', height: '135px', borderRadius: '12px', overflow: 'hidden', marginBottom: '8px' },
  imageFill: { width: '100%', height: '100%', objectFit: 'cover' },
  cardTitle: { color: '#fff', textAlign: 'center', fontSize: '0.9rem', margin: 0 },
  messageContainer: { textAlign: 'center', marginTop: '100px', maxWidth: '600px', width: '100%' },
  msgBtn: { background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(12px)', border: '1px solid rgba(255,255,255,0.3)', padding: '15px', borderRadius: '15px', color: '#fff', cursor: 'pointer', width: '180px' },
  messageDisplay: { background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(12px)', padding: '25px', borderRadius: '20px', marginTop: '30px', border: '1px solid rgba(255,255,255,0.3)' },
  overlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(8px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 2000 },
  modalContent: { background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(12px)', padding: '15px', borderRadius: '20px', border: '1px solid rgba(255,255,255,0.3)', position: 'relative' },
  modalImgFit: { maxWidth: '90vw', maxHeight: '80vh', borderRadius: '10px', objectFit: 'contain' },
  closeBtn: { position: 'absolute', top: '-40px', right: '0', background: 'none', border: 'none', color: '#fff', cursor: 'pointer' },

  mercadoMain: { width: '100%', maxWidth: '1000px', textAlign: 'center', marginTop: '100px', padding: '0 10px', boxSizing: 'border-box' },
  mercadoHeader: { color: '#ff4655', fontSize: 'clamp(1.8rem, 8vw, 3rem)', margin: 0, fontWeight: '900', letterSpacing: '2px', textShadow: '2px 2px 10px rgba(0,0,0,0.5)', wordBreak: 'break-word' },
  mercadoGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '15px', padding: '10px' },
  mercadoCard: { height: '260px', backdropFilter: 'blur(10px)', border: '2px solid', borderRadius: '8px', cursor: 'pointer', position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  cardCenter: { display: 'flex', justifyContent: 'center', alignItems: 'center' },
  diamondOuter: { width: '40px', height: '40px', border: '2px solid currentColor', transform: 'rotate(45deg)', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  diamondInner: { width: '10px', height: '10px', background: 'currentColor' },
  cardContent: { padding: '20px', zIndex: 2 },
  mercadoLabel: { color: '#fff', fontSize: '1.2rem', margin: '20px 0', textTransform: 'uppercase', textShadow: '1px 1px 3px rgba(0,0,0,0.8)' },
  glowEffect: { position: 'absolute', bottom: '-20px', left: '-20px', right: '-20px', height: '60px', filter: 'blur(40px)', opacity: 0.4, zIndex: 1 },
  downloadBtn: { background: '#00ff88', border: 'none', color: '#000', padding: '10px 15px', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold', display: 'flex', alignItems: 'center', gap: '5px', fontSize: '0.9rem', justifyContent: 'center', boxShadow: '0 4px 10px rgba(0, 255, 136, 0.2)' },

  cartasTabContainer: { display: 'flex', justifyContent: 'center', gap: '10px', marginBottom: '30px' },
  cartasTabBtn: { background: 'rgba(255,255,255,0.1)', color: '#fff', border: '1px solid rgba(255,255,255,0.3)', padding: '10px 20px', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold', transition: '0.3s' },
  cartasTabBtnActive: { background: '#ff4655', color: '#fff', border: '1px solid #ff4655', padding: '10px 20px', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold', boxShadow: '0 0 15px rgba(255,70,85,0.4)' },

  formContainer: { background: 'rgba(0,0,0,0.4)', backdropFilter: 'blur(10px)', border: '1px solid rgba(255,255,255,0.2)', borderRadius: '15px', padding: '30px', maxWidth: '500px', width: '100%', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '15px', boxSizing: 'border-box' },
  textArea: { width: '100%', height: '150px', background: 'rgba(255, 255, 255, 0.1)', border: '1px solid rgba(255,255,255,0.3)', borderRadius: '8px', color: '#fff', padding: '15px', fontSize: '1rem', fontFamily: 'inherit', resize: 'none', outline: 'none', boxSizing: 'border-box' },
  uploadBtn: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px', background: 'rgba(255, 255, 255, 0.05)', border: '1px dashed #ff4655', color: '#ff4655', padding: '15px', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold', fontSize: '0.9rem', transition: '0.3s' },

  listaCartasContainer: { display: 'flex', flexDirection: 'column', gap: '30px', maxWidth: '650px', width: '100%', margin: '0 auto' },

  cartaItem: { background: 'rgba(20, 25, 35, 0.6)', backdropFilter: 'blur(16px)', border: '1px solid rgba(255, 133, 162, 0.25)', borderRadius: '24px', padding: '30px', textAlign: 'left', display: 'flex', flexDirection: 'column', gap: '15px', boxShadow: '0 15px 35px rgba(0,0,0,0.2)', position: 'relative', overflow: 'hidden' },
  cartaGlowEfeito: { position: 'absolute', top: '-50px', left: '-50px', width: '150px', height: '150px', background: 'radial-gradient(circle, rgba(255,133,162,0.15) 0%, rgba(255,133,162,0) 70%)', zIndex: 0, pointerEvents: 'none' },

  cartaHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid rgba(255,255,255,0.05)', paddingBottom: '10px', position: 'relative', zIndex: 1 },
  cartaData: { color: '#ff85a2', fontSize: '0.85rem', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '2px' },

  cartaTexto: { color: 'rgba(255, 255, 255, 0.95)', fontSize: '1.05rem', lineHeight: '1.7', margin: '5px 0', whiteSpace: 'pre-wrap', position: 'relative', zIndex: 1, fontFamily: 'serif' },

  cartaImagemContainer: { width: '100%', borderRadius: '16px', overflow: 'hidden', boxShadow: '0 5px 15px rgba(0,0,0,0.3)', margin: '10px 0', position: 'relative', zIndex: 1 },
  cartaFotoUrl: { width: '100%', maxHeight: '400px', objectFit: 'cover', display: 'block', transition: 'transform 0.3s ease' },

  respostaBox: { background: 'linear-gradient(145deg, rgba(0, 255, 136, 0.08) 0%, rgba(0, 0, 0, 0.2) 100%)', border: '1px solid rgba(0, 255, 136, 0.2)', padding: '20px', borderRadius: '16px', marginTop: '15px', position: 'relative', zIndex: 1, boxShadow: 'inset 0 0 20px rgba(0, 255, 136, 0.02)' },
  respostaTexto: { color: '#e0f7ea', fontSize: '1rem', fontStyle: 'italic', margin: 0, lineHeight: '1.6', whiteSpace: 'pre-wrap' },

  btnResponderRafa: { background: 'rgba(255, 133, 162, 0.1)', border: '1px solid rgba(255, 133, 162, 0.4)', color: '#ff85a2', padding: '10px 20px', borderRadius: '12px', cursor: 'pointer', fontWeight: 'bold', alignSelf: 'flex-start', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.85rem', transition: 'all 0.3s ease', boxShadow: '0 4px 10px rgba(0,0,0,0.1)' },
  textAreaResposta: { width: '100%', height: '100px', background: 'rgba(0, 0, 0, 0.3)', border: '1px solid #ff85a2', borderRadius: '12px', color: '#fff', padding: '15px', fontSize: '0.95rem', fontFamily: 'inherit', resize: 'none', outline: 'none', boxShadow: 'inset 0 2px 10px rgba(0,0,0,0.2)' },
  btnSalvarResposta: { background: '#ff85a2', border: 'none', color: '#fff', padding: '10px 20px', borderRadius: '10px', cursor: 'pointer', fontWeight: 'bold', fontSize: '0.9rem', boxShadow: '0 4px 15px rgba(255,133,162,0.3)' },
  btnCancelarResposta: { background: 'transparent', border: '1px solid rgba(255,255,255,0.3)', color: '#ccc', padding: '10px 20px', borderRadius: '10px', cursor: 'pointer', fontWeight: 'bold', fontSize: '0.9rem' },
  btnMarcarLida: { marginTop: '15px', background: 'rgba(255,133,162,0.15)', border: '1px solid #ff85a2', color: '#ff85a2', padding: '8px 16px', borderRadius: '20px', cursor: 'pointer', fontWeight: 'bold', fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: '8px', transition: 'all 0.3s ease' },
  musicPageBtn: { background: '#fff', color: '#ff85a2', border: 'none', padding: '12px 25px', borderRadius: '30px', fontWeight: 'bold', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', boxShadow: '0 4px 15px rgba(0,0,0,0.1)', marginTop: '35px' },
  musicGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '20px', padding: '10px', width: '100%', maxWidth: '900px', margin: '0 auto' },
  musicCard: { display: 'flex', background: 'rgba(0, 0, 0, 0.67)', backdropFilter: 'blur(12px)', border: '1px solid rgba(255, 255, 255, 0.2)', borderRadius: '16px', padding: '15px', alignItems: 'center', gap: '15px', textAlign: 'left', boxShadow: '0 4px 20px rgba(0,0,0,0.05)' },
  musicImg: { width: '80px', height: '80px', borderRadius: '10px', objectFit: 'cover', border: '1px solid rgba(255,255,255,0.2)' },
  musicInfo: { flex: 1, display: 'flex', flexDirection: 'column' },
  audioPlayer: { width: '100%', height: '32px', borderRadius: '8px' },
  poteContainer: { width: '150px', margin: '0 auto', cursor: 'pointer' },
  poteLid: { width: '110px', height: '25px', background: 'rgba(255,255,255,0.5)', margin: '0 auto', borderRadius: '10px 10px 0 0', border: '2px solid rgba(255,255,255,0.6)', borderBottom: 'none' },
  poteBody: { width: '150px', height: '180px', background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(15px)', borderRadius: '20px', border: '2px solid rgba(255,255,255,0.4)', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', boxShadow: 'inset 0 0 20px rgba(255,255,255,0.2), 0 10px 30px rgba(0,0,0,0.1)' },
  papelMotivo: { background: '#fdfbf7', padding: '25px', borderRadius: '15px', marginTop: '40px', border: '1px solid #e0dcd3', boxShadow: '0 10px 25px rgba(0,0,0,0.15)', maxWidth: '400px', margin: '40px auto 0 auto' },
  timerContainer: { display: 'flex', flexWrap: 'wrap', gap: '15px', justifyContent: 'center', marginTop: '30px' },
  timeBox: { background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(10px)', border: '1px solid rgba(255,255,255,0.2)', borderRadius: '15px', padding: '20px', minWidth: '100px', display: 'flex', flexDirection: 'column', alignItems: 'center' },
  timeNum: { color: '#ff85a2', fontSize: '2.5rem', fontWeight: 'bold', margin: '0' },
  timeLabel: { color: '#fff', fontSize: '0.9rem', textTransform: 'uppercase', letterSpacing: '1px', marginTop: '5px' },
  timeline: { position: 'relative', maxWidth: '600px', margin: '0 auto', padding: '20px 0', textAlign: 'left' },
  timelineLine: { position: 'absolute', left: '14px', top: '0', bottom: '0', width: '2px', background: 'rgba(255, 133, 162, 0.4)', zIndex: 1 },
  timelineItem: { display: 'flex', gap: '20px', marginBottom: '40px', position: 'relative', zIndex: 2 },
  timelineDot: { width: '30px', height: '30px', background: '#ff85a2', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, boxShadow: '0 0 10px rgba(255, 133, 162, 0.8)' },
  timelineContent: { background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(10px)', border: '1px solid rgba(255,255,255,0.2)', padding: '20px', borderRadius: '15px', flex: 1 },
  timelineDate: { color: '#ff85a2', fontSize: '0.85rem', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '1px' },
  timelineTitle: { color: '#fff', margin: '5px 0 10px 0', fontSize: '1.2rem' },
  timelineText: { color: '#ddd', margin: 0, fontSize: '0.95rem', lineHeight: '1.5' },

  mapPageWrapper: { width: '100%', maxWidth: '1200px', marginTop: '90px', padding: '0 10px', boxSizing: 'border-box' },
  mapLayoutContainer: { display: 'flex', gap: '15px', background: 'rgba(0,0,0,0.2)', backdropFilter: 'blur(10px)', borderRadius: '20px', padding: '15px', border: '1px solid rgba(255,255,255,0.1)', flexDirection: 'column' },
  mapSidebar: { width: '100%', display: 'flex', flexDirection: 'row', gap: '10px', overflowX: 'auto', paddingBottom: '8px', boxSizing: 'border-box', WebkitOverflowScrolling: 'touch' },
  sidebarCard: { padding: '10px 15px', borderRadius: '12px', cursor: 'pointer', textAlign: 'left', backdropFilter: 'blur(5px)', transition: '0.2s', flexShrink: 0, minWidth: '180px' },
  mapWrapperBox: { width: '100%', height: '350px', borderRadius: '15px', overflow: 'hidden', border: '2px solid rgba(255,255,255,0.1)', boxShadow: '0 10px 30px rgba(0,0,0,0.5)', position: 'relative', zIndex: 1 },
  popupContent: { display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center' },
  popupImage: { width: '100%', height: '120px', objectFit: 'cover', borderRadius: '10px' },

  ceuMain: { width: '100%', maxWidth: '800px', textAlign: 'center', marginTop: '90px', padding: '0 10px', boxSizing: 'border-box' },
  espacoCeu: { width: '100%', height: '500px', background: 'radial-gradient(ellipse at bottom, #1b2735 0%, #090a0f 100%)', borderRadius: '20px', position: 'relative', overflow: 'hidden', border: '1px solid rgba(255,255,255,0.1)', boxShadow: '0 10px 30px rgba(0,0,0,0.5)' },
  estrelaBrilho: { cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', width: '30px', height: '30px', filter: 'drop-shadow(0 0 5px #fff)' },
  estrelaCadente: { position: 'absolute', width: '3px', height: '3px', background: '#fff', borderRadius: '50%', boxShadow: '0 0 10px 2px #fff, 0 0 20px #ff85a2', transform: 'rotate(-45deg)' },
  popupEstrelaFixo: { position: 'absolute', bottom: '15px', left: '15px', right: '15px', background: 'rgba(15, 25, 35, 0.85)', backdropFilter: 'blur(10px)', border: '1px solid rgba(255, 255, 255, 0.15)', padding: '15px', borderRadius: '12px', zIndex: 50, textAlign: 'center', boxShadow: '0 8px 32px rgba(0, 0, 0, 0.5)' },

  diarioGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: '15px', padding: '10px', width: '100%' },
  diarioCard: { border: '1px solid', borderRadius: '15px', padding: '20px 10px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', transition: '0.3s', backdropFilter: 'blur(5px)', boxShadow: '0 5px 15px rgba(0,0,0,0.2)' }
};
